spring.application.name=springboot
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.enable-spring-security=false
spring.security.user.name=admin
spring.security.user.password=admin
springdoc.swagger-ui.tags-sorter=alpha

springdoc.swagger-ui.operations-sorter: alpha
springdoc.swagger-ui.enabled: true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.paths-to-match= /**
#springdoc.group-configs= platform
springdoc.packages-to-scan:org.example.springboot

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tourism_system_update?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=96962011
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-built-in-alias-types=true
server.port=1236

user.defaultPassword=123456
spring.mail.host=smtp.qq.com
spring.mail.username=3073658197@qq.com
spring.mail.password=ccaxnykrmhxidfgb
spring.mail.default-encoding=utf-8
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.port=587
user.fromEmail=3073658197@qq.com


# application.properties
server.servlet.context-path=/
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
mybatis-plus.mapper-locations=classpath:/mapper/*.xml
spring.jackson.default-property-inclusion=non_empty

# application.properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


knife4j.enable=true
knife4j.setting.language=zh_cn
knife4j.basic.enable=true
knife4j.basic.username=admin
knife4j.basic.password=admin
alipay.appId=9021000162621708
alipay.privateKey=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCD5MyIk0lRBwehxSvWnrx0MIUyEQOeKenVXuO+bVRmXOPXSgId3sKoOf4/LwoqASXEuzOWwDFxnydfRSr+w+oSVR/hBtgnYt+M0A4qZiQJNNB4pycexe1K7+99dEFAxAQNiCpbMzLRzxbR1h+jB5jwPE6SNOyezKCLoGfY3Mr8JUZglQCrvZJkOWgUV2oqJMEWKwjXRIdsfuJud3wbZOOBBHqqt7q8WrOshStjPRJg34vZ8k6CXyfeOjFgvis7NXkMzVwK0ucOzMjTIGwoR1SwjxxKRntO/hJdIx+B0ue520GBBiDDamV9xZD4UC+w8FVVcnpGau9Qie/vcXofxj/PAgMBAAECggEAO4rE0zs6s/uqdFtgyQjsJr/owYtwyKw/RfYKdmNA4N06dmyQvA9ebTeREdEYk5HlDQU96uZk69hfm+DL4itrtk77j0jZuB4osZcTbgyiZA2Vt4IuZPQRhez/fvFGrAhRlBJOnNFmNdV5hc1WhvDdGEcBaXu+/ol+SMpnVz2F3YIIMrD2Yg4mNaU1wI8izT9h2VqNq+cQcPWuhdzpHcznrvs6w3yQ1hRgY4iCmqdpC/tTd5p00mesSjcRNHuODjsMTq0feCTTLRLIG6dnas69NxMyoCUoha/qqJmyQ+LZjljP5PL13IaPV9PYPCxcrU0JIEtyMi5E4ClPTLuw1rTy0QKBgQDCTkBLrG9RIGUcu80k8WYiPUoz0VGrKukaJDGesCSgpH0ffLJp/rk6rxsT24KDUrBOQZCh3KPev138Y6wKCQ1k22DeYIYfEM+44zm0/aJntwDFmvw9B4Hm+g+lDr0vqsfIUTiheyqDMaOgM1Pfmp3tbLYr9tzLBphaVm2rkvNg8wKBgQCtxYTku/uVmKpwBKcbWzubxxofJ+4meqzAUPUtpBluoMPXTkizPOtc69MDjLH+xH6buqE3aaAXu06ro4sA+Ze6rJeC1B/uaUP8uWkV8mZrB5Hjiivvg8GYmPHqXiKz8neIFryrVEGDBwETrKqN7C9/PiIXrjrBOoFupIgg1Y98tQKBgD9UIcCIQv+9/zaOPx57Tz55m2WoI2YWZkMO6N0/q7Bv7BgHHF9Pli96QukF8lO675uR4wHeV8qRtKA+HCRpLuRgXAIek5gscodgB77lq7kB/E5rZSq+96fAeLjjROX0U4kGb96xtflshFgCYqPOUQrBE97gZrYFQEKxSK1TB9/hAoGAKxj30rsEtJ9+dfXRdCl2aTZCNkPy/rwiKDhr9nviitt4dufFhB6xyQP7+79jTepx9DGfVlzuBbTA2DThfsZoaTXxBdOSb9DPudhKRdUurZDdD+/u4aJt22jjZtseBD84ghoRhPSKovKTw8tpKXXQeeBxGCpwDAh0nXpVAL+2rJkCgYEAwQGv0n0sCXuL7cCE3vxDKh1HWn2aORPXucJ2KbGyeIn1g6KGKtnEQ9IGEmF1ISQgE6FFKUCfHm4bmGCN85c+yI/kR7szIjHUr7DTdy0M3C5sHRATRw4NWzHhPE4aHrfR3m9rBsST7FZR01DbB77tdTzseUWGKNQY13ASAEfSaWA=
alipay.publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlYH3PQMsIZ7Lu4sAp/cAgisGBaDI2TPmhDJUPjN57tXFEJxjlIOyApt5J7NN9p2KTZthrK6YLhInv4tvh6igYXvr7NTO0/IXYkefwbZejaUtoTzcecDUxBxPczr9C/UToeP+hvMdIoX9bcK01OziXpzlTQdLY7/PPPWzwHbVwW7zEKsbbLRczbCXlkIxuYc60TtjpCllBkkuZjLeAJMSULbxlLJExeSvmVtaVYVjxKvpye87oi7IY/qBUM2Qv/H4dKe3m42z6RL1/gWMEMY1N7B1scdfPFaUZR0nyIVgR4tC39bqPANQ1aEUIReyELuTAgdrL3ibo7wxnf6QPk6SoQIDAQAB

alipay.gateway=https://openapi-sandbox.dl.alipaydev.com/gateway.do
alipay.returnUrl=http://localhost:8080/payment/result
alipay.notifyUrl=http://b6687697.natappfree.cc/api/alipay/notify
alipay.charset=UTF-8
alipay.format=json
alipay.signType=RSA2

# Redis配置
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=10000
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0


# ==================== Spring AI OpenAI  ====================

spring.ai.openai.api-key=sk-imbdqncmhtdzazyuyfuczrcjfyryiqyaohyklnvzxmbgifnf
spring.ai.openai.base-url=https://api.siliconflow.cn
spring.ai.openai.chat.options.model=deepseek-ai/DeepSeek-V3
spring.ai.openai.chat.completions-path=/v1/chat/completions

spring.ai.openai.chat.options.temperature=0.7

spring.ai.openai.chat.options.max-tokens=2000